# Generated by Django 4.2.6 on 2024-06-27 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_author_alter_taskcard_attachment_path_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
